/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.forms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author rastko
 */
public class FrmAdministrator extends javax.swing.JFrame {

    /** Creates new form FrmAdministrator */
    public FrmAdministrator() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLawyer = new javax.swing.JMenu();
        jMenuItemAddLawyer = new javax.swing.JMenuItem();
        jMenuItemViewLawyer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Law Office Manager - Administration");

        lblUser.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblUser.setText("User: ");

        jMenuLawyer.setText("Lawyer");

        jMenuItemAddLawyer.setText("Add");
        jMenuLawyer.add(jMenuItemAddLawyer);

        jMenuItemViewLawyer.setText("View all");
        jMenuItemViewLawyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewLawyerActionPerformed(evt);
            }
        });
        jMenuLawyer.add(jMenuItemViewLawyer);

        jMenuBar1.add(jMenuLawyer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemViewLawyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewLawyerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemViewLawyerActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAddLawyer;
    private javax.swing.JMenuItem jMenuItemViewLawyer;
    private javax.swing.JMenu jMenuLawyer;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblWelcome() {
        return lblUser;
    }
    
    public void jmiLawyerNewAddActionListener(ActionListener actionListener){
        jMenuItemAddLawyer.addActionListener(actionListener);
    }
    
    public void jmiLawyerViewAddActionListener(ActionListener actionListener){
        jMenuItemViewLawyer.addActionListener(actionListener);
    }
}
